// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apigen

import (
	"time"

	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CEFRLevel.
const (
	A1 CEFRLevel = "A1"
	A2 CEFRLevel = "A2"
	B1 CEFRLevel = "B1"
	B2 CEFRLevel = "B2"
	C1 CEFRLevel = "C1"
	C2 CEFRLevel = "C2"
)

// Valid indicates whether the value is a known member of the CEFRLevel enum.
func (e CEFRLevel) Valid() bool {
	switch e {
	case A1:
		return true
	case A2:
		return true
	case B1:
		return true
	case B2:
		return true
	case C1:
		return true
	case C2:
		return true
	default:
		return false
	}
}

// Defines values for EnglishVariant.
const (
	AmE EnglishVariant = "AmE"
	BrE EnglishVariant = "BrE"
)

// Valid indicates whether the value is a known member of the EnglishVariant enum.
func (e EnglishVariant) Valid() bool {
	switch e {
	case AmE:
		return true
	case BrE:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Student Role = "student"
	Teacher Role = "teacher"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Student:
		return true
	case Teacher:
		return true
	default:
		return false
	}
}

// CEFRLevel Learner difficulty band (CEFR), A1 easiest … C2 hardest.
type CEFRLevel string

// EnglishVariant Accent and spelling convention — British or American.
type EnglishVariant string

// Error defines model for Error.
type Error struct {
	// Error Human-readable message.
	Error string `json:"error"`
}

// LearningSettings A learner's two onboarding choices; both are always set together.
type LearningSettings struct {
	// CefrLevel Learner difficulty band (CEFR), A1 easiest … C2 hardest.
	CefrLevel CEFRLevel `json:"cefr_level"`

	// EnglishVariant Accent and spelling convention — British or American.
	EnglishVariant EnglishVariant `json:"english_variant"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	ActiveRole Role `json:"active_role"`

	// LearningSettings Null until the learner finishes onboarding.
	LearningSettings *LearningSettings `json:"learning_settings,omitempty"`

	// Onboarded Server-derived — true once learning_settings is set. Clients read this rather than re-deriving from null.
	Onboarded bool `json:"onboarded"`
	User      User `json:"user"`
}

// Role defines model for Role.
type Role string

// User defines model for User.
type User struct {
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`

	// Email Omitted if not set.
	Email *openapi_types.Email `json:"email,omitempty"`
	Id    openapi_types.UUID   `json:"id"`
	Phone string               `json:"phone"`

	// Roles A user may hold both student and teacher.
	Roles     []Role    `json:"roles"`
	UpdatedAt time.Time `json:"updated_at"`
}

// AuthError defines model for AuthError.
type AuthError = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Current user + active role
	// (GET /api/v1/me)
	GetCurrentUser(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentUser(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/me", wrapper.GetCurrentUser)
}
